# Checks that some critical dexpreopt output files are installed.

# Inputs:
# DISABLE_DEXPREOPT_CHECK: True if the check should be disabled.
# ALL_DEFAULT_INSTALLED_MODULES: The full list of modules going to be installed.
# DEXPREOPT_SYSTEMSERVER_ARTIFACTS: The list of compilation artifacts of system server jars, which
# 	is generated by Soong in dexpreopt_check.go.

ifneq (true,$(DISABLE_DEXPREOPT_CHECK))
  ifneq (,$(filter services,$(PRODUCT_PACKAGES)))
    $(foreach artifact,$(DEXPREOPT_SYSTEMSERVER_ARTIFACTS), \
      $(if $(filter $(artifact),$(ALL_DEFAULT_INSTALLED_MODULES)),, \
        $(error Missing compilation artifact $(artifact). Dexpreopting is not working for some system server jars) \
      ) \
    )
  endif
endif
