# Checks that some critical dexpreopt output files are installed.

# Inputs:
# DISABLE_DEXPREOPT_CHECK: True if the check should be disabled.
# PRODUCT_BROKEN_DEPRECATED_MK_SYSTEM_SERVER_JARS: True if the product uses system server jars
#   defined as Android.mk modules. The check will be disabled if true because dexpreopting is
#   currently not working for such jars.
# PRODUCT_PACKAGES: The list of packages to be installed for the product.
# ALL_DEFAULT_INSTALLED_MODULES: The full list of modules going to be installed.
# DEXPREOPT_SYSTEMSERVER_ARTIFACTS: The list of compilation artifacts of system server jars, which
# 	is generated by Soong in dexpreopt_check.go.

DISABLE_DEXPREOPT_CHECK ?= PRODUCT_BROKEN_DEPRECATED_MK_SYSTEM_SERVER_JARS

ifneq (true,$(DISABLE_DEXPREOPT_CHECK))
  # Skip the check if the system server is not installed for the product.
  ifneq (,$(filter services,$(PRODUCT_PACKAGES)))
    $(call maybe-print-list-and-error,\
      $(filter-out $(ALL_DEFAULT_INSTALLED_MODULES),$(DEXPREOPT_SYSTEMSERVER_ARTIFACTS)),\
      Missing compilation artifacts. Dexpreopting is not working for some system server jars \
    )
  endif
endif
