###########################################################
## Builds a Java 9 system image, suitable for javac --system
##
###########################################################

LOCAL_MODULE_CLASS := JAVA_LIBRARIES
LOCAL_BUILT_MODULE_STEM := system-modules
#include $(BUILD_SYSTEM)/config.mk

LOCAL_CLASSES := $(call local-intermediates-dir,COMMON)/classes
LOCAL_CLASSPATH_ENTRIES := $(call java-lib-header-files,$(LOCAL_JAVA_LIBRARIES))
LOCAL_MODULE_DIR := $(call local-intermediates-dir,COMMON)/module
LOCAL_MODULE_INFO := $(LOCAL_MODULE_DIR)/module-info
LOCAL_MODULE_NAME := java.base
LOCAL_JMOD_DIR := $(call local-intermediates-dir,COMMON)/jmod
LOCAL_JMOD_FILE := $(LOCAL_JMOD_DIR)/$(LOCAL_MODULE_NAME).jmod
LOCAL_SYSTEM_MODULES := $(call local-intermediates-dir,COMMON)/system-modules

$(LOCAL_MODULE_INFO).class: PRIVATE_MODULE_DIR := $(LOCAL_MODULE_DIR)
$(LOCAL_MODULE_INFO).class: PRIVATE_MODULE_INFO := $(LOCAL_MODULE_INFO)
$(LOCAL_MODULE_INFO).class: PRIVATE_MODULE_NAME := $(LOCAL_MODULE_NAME)
$(LOCAL_MODULE_INFO).class: PRIVATE_CLASSPATH_ENTRIES := $(LOCAL_CLASSPATH_ENTRIES)
$(LOCAL_MODULE_INFO).class: $(LOCAL_CLASSPATH_ENTRIES)
	rm -rf $(PRIVATE_MODULE_DIR)
	mkdir -p $(PRIVATE_MODULE_DIR)
	echo "module $(PRIVATE_MODULE_NAME) {" > $(PRIVATE_MODULE_INFO).java
	build/tools/list-jar-packages.sh $(PRIVATE_CLASSPATH_ENTRIES) \
	      | sed 's/^/    exports /' \
	      | sed 's/$$/;/' \
          >> $(PRIVATE_MODULE_INFO).java
	echo "}" >> $(PRIVATE_MODULE_INFO).java
	$(JAVAC) --patch-module=java.base=$(call normalize-path-list,$(PRIVATE_CLASSPATH_ENTRIES)) $(PRIVATE_MODULE_INFO).java

$(LOCAL_CLASSES): PRIVATE_MODULE_INFO := $(LOCAL_MODULE_INFO)
$(LOCAL_CLASSES): PRIVATE_CLASSES := $(LOCAL_CLASSES)
$(LOCAL_CLASSES): PRIVATE_CLASSPATH_ENTRIES := $(LOCAL_CLASSPATH_ENTRIES)
$(LOCAL_CLASSES): $(LOCAL_MODULE_INFO).class $(LOCAL_CLASSPATH_ENTRIES)
	rm -rf $(PRIVATE_CLASSES)
	mkdir -p $(PRIVATE_CLASSES)
	$(call unzip-jar-files,$(PRIVATE_CLASSPATH_ENTRIES),$(PRIVATE_CLASSES))
	cp $(PRIVATE_MODULE_INFO).class $(PRIVATE_CLASSES)/

$(LOCAL_JMOD_FILE): PRIVATE_JMOD_DIR := $(LOCAL_JMOD_DIR)
$(LOCAL_JMOD_FILE): PRIVATE_JMOD_FILE := $(LOCAL_JMOD_FILE)
$(LOCAL_JMOD_FILE): PRIVATE_CLASSES := $(LOCAL_CLASSES)
$(LOCAL_JMOD_FILE): $(LOCAL_CLASSPATH_ENTRIES) $(LOCAL_CLASSES)
	rm -rf $(PRIVATE_JMOD_DIR)
	mkdir -p $(PRIVATE_JMOD_DIR)
	$(JMOD) create \
	    --module-version 9 \
	    --target-platform $(HOST_OS)-$(HOST_ARCH) \
	    --class-path $(PRIVATE_CLASSES) \
	    --module-path $(PRIVATE_JMOD_DIR) $(PRIVATE_JMOD_FILE)

$(LOCAL_SYSTEM_MODULES): PRIVATE_SYSTEM_MODULES := $(LOCAL_SYSTEM_MODULES)
$(LOCAL_SYSTEM_MODULES): PRIVATE_JMOD_DIR := $(LOCAL_JMOD_DIR)
$(LOCAL_SYSTEM_MODULES): PRIVATE_MODULE_NAME := $(LOCAL_MODULE_NAME)
$(LOCAL_SYSTEM_MODULES): $(LOCAL_JMOD_FILE)
	rm -rf $(PRIVATE_SYSTEM_MODULES)
	$(JLINK) --module-path $(PRIVATE_JMOD_DIR) --add-modules $(PRIVATE_MODULE_NAME) --output $(PRIVATE_SYSTEM_MODULES)
	mkdir -p $(PRIVATE_SYSTEM_MODULES)/lib
	cp $(ANDROID_JAVA_HOME)/lib/jrt-fs.jar $(PRIVATE_SYSTEM_MODULES)/lib/

$(LOCAL_MODULE): $(LOCAL_SYSTEM_MODULES)

LOCAL_CLASSES:=
LOCAL_CLASSPATH_ENTRIES:=
LOCAL_MODULE_DIR:=
LOCAL_MODULE_INFO:=
LOCAL_MODULE_NAME:=
LOCAL_JMOD_DIR:=
LOCAL_JMOD_FILE:=
LOCAL_SYSTEM_MODULES:=
