#!/bin/bash

set -ex

local BUG_ID='0'

PLATFORM_CODENAME='UpsideDownCake'
PLATFORM_CODENAME_JAVA='UPSIDE_DOWN_CAKE'
PLATFORM_SDK_VERSION='34'
PLATFORM_VERSION='14'

BUILD_PREFIX='UP1A'

MAINLINE_EXTENSION='6'
MAINLINE_SDK_COMMIT_MESSAGE=''
MAINLINE_SDK_BUILD_ID=0
