# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: care_map.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='care_map.proto',
  package='UpdateVerifier',
  syntax='proto3',
  serialized_pb=_b('\n\x0e\x63\x61re_map.proto\x12\x0eUpdateVerifier\"\x88\x01\n\x07\x43\x61reMap\x12\x39\n\npartitions\x18\x01 \x03(\x0b\x32%.UpdateVerifier.CareMap.PartitionInfo\x1a\x42\n\rPartitionInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06ranges\x18\x02 \x01(\t\x12\x13\n\x0b\x66ingerprint\x18\x03 \x01(\tB\x02H\x03\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CAREMAP_PARTITIONINFO = _descriptor.Descriptor(
  name='PartitionInfo',
  full_name='UpdateVerifier.CareMap.PartitionInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='UpdateVerifier.CareMap.PartitionInfo.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ranges', full_name='UpdateVerifier.CareMap.PartitionInfo.ranges', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fingerprint', full_name='UpdateVerifier.CareMap.PartitionInfo.fingerprint', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=171,
)

_CAREMAP = _descriptor.Descriptor(
  name='CareMap',
  full_name='UpdateVerifier.CareMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='partitions', full_name='UpdateVerifier.CareMap.partitions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CAREMAP_PARTITIONINFO, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=171,
)

_CAREMAP_PARTITIONINFO.containing_type = _CAREMAP
_CAREMAP.fields_by_name['partitions'].message_type = _CAREMAP_PARTITIONINFO
DESCRIPTOR.message_types_by_name['CareMap'] = _CAREMAP

CareMap = _reflection.GeneratedProtocolMessageType('CareMap', (_message.Message,), dict(

  PartitionInfo = _reflection.GeneratedProtocolMessageType('PartitionInfo', (_message.Message,), dict(
    DESCRIPTOR = _CAREMAP_PARTITIONINFO,
    __module__ = 'care_map_pb2'
    # @@protoc_insertion_point(class_scope:UpdateVerifier.CareMap.PartitionInfo)
    ))
  ,
  DESCRIPTOR = _CAREMAP,
  __module__ = 'care_map_pb2'
  # @@protoc_insertion_point(class_scope:UpdateVerifier.CareMap)
  ))
_sym_db.RegisterMessage(CareMap)
_sym_db.RegisterMessage(CareMap.PartitionInfo)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
# @@protoc_insertion_point(module_scope)
